// <auto-generated />
using EmployeeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229212419_DepartmentData")]
    partial class DepartmentData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeAPI.Model.Department", b =>
                {
                    b.Property<int>("CodeDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeDepartment"));

                    b.Property<string>("NameDepartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeDepartment");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            CodeDepartment = 1,
                            NameDepartment = "Dirección general"
                        },
                        new
                        {
                            CodeDepartment = 2,
                            NameDepartment = "Talento Humano"
                        },
                        new
                        {
                            CodeDepartment = 3,
                            NameDepartment = "Finanzas"
                        },
                        new
                        {
                            CodeDepartment = 4,
                            NameDepartment = "Marketing"
                        },
                        new
                        {
                            CodeDepartment = 5,
                            NameDepartment = "Comercial"
                        },
                        new
                        {
                            CodeDepartment = 6,
                            NameDepartment = "Operaciones"
                        },
                        new
                        {
                            CodeDepartment = 7,
                            NameDepartment = "Compras y Logística"
                        },
                        new
                        {
                            CodeDepartment = 8,
                            NameDepartment = "Tecnología"
                        },
                        new
                        {
                            CodeDepartment = 9,
                            NameDepartment = "Atención al Cliente"
                        });
                });

            modelBuilder.Entity("EmployeeAPI.Model.Employee", b =>
                {
                    b.Property<int>("CodeEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeEmployee"));

                    b.Property<int>("CodeGroup")
                        .HasColumnType("int");

                    b.Property<int>("CodeLeader")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEmployee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodeEmployee");

                    b.HasIndex("CodeGroup");

                    b.HasIndex("CodeLeader");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeAPI.Model.Group", b =>
                {
                    b.Property<int>("CodeGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeGroup"));

                    b.Property<int>("CodeDepartment")
                        .HasColumnType("int");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeGroup");

                    b.HasIndex("CodeDepartment");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("EmployeeAPI.Model.Employee", b =>
                {
                    b.HasOne("EmployeeAPI.Model.Group", "Group")
                        .WithMany("Employees")
                        .HasForeignKey("CodeGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeAPI.Model.Employee", "Leader")
                        .WithMany()
                        .HasForeignKey("CodeLeader")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("EmployeeAPI.Model.Group", b =>
                {
                    b.HasOne("EmployeeAPI.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("CodeDepartment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeAPI.Model.Group", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
